
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class ConVehiculos extends javax.swing.JFrame {

    /**
     * Creates new form ConVehiculos
     */
    public ConVehiculos() {
        initComponents();
         getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVehiculos = new javax.swing.JButton();
        btnVehiculoMatriculas = new javax.swing.JButton();
        btnVehiculosDisponibles = new javax.swing.JButton();
        VehiculoMarca = new javax.swing.JButton();
        VehiculosGama = new javax.swing.JButton();
        btnVehiculosRentados = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        VehiculoPrecio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVehiculos.setBackground(new java.awt.Color(102, 204, 255));
        btnVehiculos.setText("Todos los Vehiculos");
        btnVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculosActionPerformed(evt);
            }
        });

        btnVehiculoMatriculas.setBackground(new java.awt.Color(102, 204, 255));
        btnVehiculoMatriculas.setText("Vehiculos por Matricula");
        btnVehiculoMatriculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculoMatriculasActionPerformed(evt);
            }
        });

        btnVehiculosDisponibles.setBackground(new java.awt.Color(102, 204, 255));
        btnVehiculosDisponibles.setText("Vehiculos Disponibles");
        btnVehiculosDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculosDisponiblesActionPerformed(evt);
            }
        });

        VehiculoMarca.setBackground(new java.awt.Color(102, 204, 255));
        VehiculoMarca.setText("Vehiculos por Marca");
        VehiculoMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehiculoMarcaActionPerformed(evt);
            }
        });

        VehiculosGama.setBackground(new java.awt.Color(102, 204, 255));
        VehiculosGama.setText("Vehiculos por Gama ");
        VehiculosGama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehiculosGamaActionPerformed(evt);
            }
        });

        btnVehiculosRentados.setBackground(new java.awt.Color(102, 204, 255));
        btnVehiculosRentados.setText("Vehiculos Rentados");
        btnVehiculosRentados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculosRentadosActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(255, 102, 102));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        VehiculoPrecio.setBackground(new java.awt.Color(102, 204, 255));
        VehiculoPrecio.setText("Vehiculos Por Precio");
        VehiculoPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehiculoPrecioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVehiculosRentados)
                    .addComponent(btnVehiculoMatriculas)
                    .addComponent(btnVehiculosDisponibles))
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(VehiculosGama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VehiculoMarca)
                    .addComponent(VehiculoPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(btnVolver)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(btnVehiculos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnVehiculos)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VehiculoMarca)
                    .addComponent(btnVehiculoMatriculas))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VehiculosGama)
                    .addComponent(btnVehiculosDisponibles))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVehiculosRentados)
                    .addComponent(VehiculoPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VehiculosGamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehiculosGamaActionPerformed
        new VehiculosGama().setVisible(true);
    }//GEN-LAST:event_VehiculosGamaActionPerformed

    private void btnVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculosActionPerformed
      new Vehiculos().setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_btnVehiculosActionPerformed

    private void btnVehiculoMatriculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculoMatriculasActionPerformed
      new VehiculosMatricula().setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_btnVehiculoMatriculasActionPerformed

    private void btnVehiculosDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculosDisponiblesActionPerformed
      new VehiculosDisponibles().setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_btnVehiculosDisponiblesActionPerformed

    private void btnVehiculosRentadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculosRentadosActionPerformed
      new VehiculosRentados().setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_btnVehiculosRentadosActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
      this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void VehiculoMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehiculoMarcaActionPerformed
       new VehiculosMarca().setVisible(true);
    }//GEN-LAST:event_VehiculoMarcaActionPerformed

    private void VehiculoPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehiculoPrecioActionPerformed
       new VehiculosPrecio().setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_VehiculoPrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConVehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VehiculoMarca;
    private javax.swing.JButton VehiculoPrecio;
    private javax.swing.JButton VehiculosGama;
    private javax.swing.JButton btnVehiculoMatriculas;
    private javax.swing.JButton btnVehiculos;
    private javax.swing.JButton btnVehiculosDisponibles;
    private javax.swing.JButton btnVehiculosRentados;
    private javax.swing.JButton btnVolver;
    // End of variables declaration//GEN-END:variables
}
