/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.SimpleDateFormat;

/**
 *
 * @author DELL
 */
public class ReservaVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form ReservaVehiculo
     */
    public ReservaVehiculo() {
        initComponents();
    txtMatricula.setEditable(false);
    txtFecha.setEnabled(false);
    txtObservacion.setEditable(false);

    btnGuardar.setEnabled(false);
    btnBuscar.setEnabled(true);

    lblEstado.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        txtRecepcion = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        txtObservacion = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JToggleButton();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        txtFecha = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Resepcion: ");

        jLabel2.setText("ID Matricula:");

        jLabel3.setText("Fecha de Recepcion:");

        jLabel4.setText("Observacion:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(txtRecepcion)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtObservacion)
                                    .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(34, 34, 34)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnGuardar)
                .addGap(79, 79, 79)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnVolver))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

    if (txtRecepcion.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "ID Recepción es obligatorio");
        txtRecepcion.requestFocus();
        return;
    }

    File archivo = new File("datos/recepcion.txt");
    boolean encontrado = false;

    try {
        if (archivo.exists()) {
            BufferedReader br = new BufferedReader(new FileReader(archivo));
            String linea;

            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split("\\|");

                if (datos[0].equals(txtRecepcion.getText())) {

                    txtMatricula.setText(datos[1]);
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                    Date fecha = sdf.parse(datos[2]);
                    txtFecha.setDate(fecha);
                    txtObservacion.setText(datos[3]);

                    lblEstado.setText("Modificando...");
                    encontrado = true;
                    break;
                }
            }
            br.close();
        }

        if (!encontrado) {
            lblEstado.setText("Creando...");
            txtMatricula.setText("");
            txtFecha.setDate(null);
            txtObservacion.setText("");

            JOptionPane.showMessageDialog(
                this,
                "La recepción no existe.\nPuede crear una nueva."
            );
        }

        txtMatricula.setEditable(true);
        txtFecha.setEnabled(true);
        txtObservacion.setEditable(true);

        txtRecepcion.setEditable(false);
        btnBuscar.setEnabled(false);
        btnGuardar.setEnabled(true);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al buscar recepción");
    }
 // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

    txtRecepcion.setText("");
    txtMatricula.setText("");
    txtFecha.setDate(null);
    txtObservacion.setText("");
    lblEstado.setText("");

    txtRecepcion.setEditable(true);
    txtMatricula.setEditable(false);
    txtFecha.setEnabled(false);
    txtObservacion.setEditable(false);

    btnBuscar.setEnabled(true);
    btnGuardar.setEnabled(false);

    txtRecepcion.requestFocus();
   // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
     
    if (txtRecepcion.getText().trim().isEmpty() ||
        txtMatricula.getText().trim().isEmpty() ||
        txtFecha.getDate() == null) {

        JOptionPane.showMessageDialog(this,
            "Id Recepción, Matrícula y Fecha son obligatorios");
        return;
    }

    
    
    Date fechaRecepcion = txtFecha.getDate();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    String fechaTexto = sdf.format(fechaRecepcion);

    
    File archivoReservas = new File("datos/reservas.txt");
    Date fechaEntrada = null;

    try {
        if (archivoReservas.exists()) {
            BufferedReader br = new BufferedReader(new FileReader(archivoReservas));
            String linea;

            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split("\\|");

                
                if (datos.length >= 3 && datos[1].equals(txtMatricula.getText())) {
                    fechaEntrada = sdf.parse(datos[2]);
                    break;
                }
            }
            br.close();
        }

        if (fechaEntrada != null && fechaRecepcion.before(fechaEntrada)) {
            JOptionPane.showMessageDialog(this,
                "La fecha de recepción no puede ser menor\n" +
                "que la fecha de entrada en reservas");
            return;
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error validando la fecha con reservas");
        return;
    }

   
    String observacion = txtObservacion.getText().trim();

    
    File archivo = new File("datos/recepcion.txt");
    archivo.getParentFile().mkdirs();

    try {
        ArrayList<String> lista = new ArrayList<>();
        boolean actualizado = false;

        if (archivo.exists()) {
            BufferedReader br = new BufferedReader(new FileReader(archivo));
            String linea;

            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split(";");

                if (datos[0].equals(txtRecepcion.getText())) {

                    String nuevaLinea =
                        txtRecepcion.getText() + ";" +
                        txtMatricula.getText() + ";" +
                        fechaTexto + ";" +
                        observacion;

                    lista.add(nuevaLinea);
                    actualizado = true;
                } else {
                    lista.add(linea);
                }
            }
            br.close();
        }

        if (!actualizado) {
            String nuevaLinea =
                txtRecepcion.getText() + ";" +
                txtMatricula.getText() + ";" +
                fechaTexto + ";" +
                observacion;

            lista.add(nuevaLinea);
        }

        BufferedWriter bw = new BufferedWriter(new FileWriter(archivo));
        for (String l : lista) {
            bw.write(l);
            bw.newLine();
        }
        bw.close();

        JOptionPane.showMessageDialog(this,
            actualizado ? "Recepción modificada correctamente"
                        : "Recepción creada correctamente");

        limpiarFormulario();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al guardar recepción");
        e.printStackTrace();
    }

  // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed
private void limpiarFormulario() {

    txtRecepcion.setText("");
    txtMatricula.setText("");
   txtFecha.setDate(null);
    txtObservacion.setText("");
    lblEstado.setText("");

    txtRecepcion.setEditable(true);
    txtMatricula.setEditable(false);
    txtFecha.setEnabled(false);
    txtObservacion.setEditable(false);

    btnBuscar.setEnabled(true);
    btnGuardar.setEnabled(false);

    txtRecepcion.requestFocus();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservaVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblEstado;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtObservacion;
    private javax.swing.JTextField txtRecepcion;
    // End of variables declaration//GEN-END:variables
}
