
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jeanc
 */
public class VehiculosPrecio extends javax.swing.JFrame {

    /**
     * Creates new form VehiculosPrecio
     */
    public VehiculosPrecio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtPrecioInicial = new javax.swing.JTextField();
        TxtPrecioFinal = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPrecio = new javax.swing.JTable();
        BtnVolver = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Precio: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setText("Desde:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel3.setText("Hasta:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));
        jPanel1.add(TxtPrecioInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 80, 20));
        jPanel1.add(TxtPrecioFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 80, 20));

        BtnBuscar.setBackground(new java.awt.Color(102, 204, 255));
        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, -1));

        TablaPrecio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Marca", "Modelo", "Tipo", "Motor", "Gama", "Precio"
            }
        ));
        jScrollPane1.setViewportView(TablaPrecio);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 760, 240));

        BtnVolver.setBackground(new java.awt.Color(255, 102, 102));
        BtnVolver.setText("Volver");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(BtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        BtnLimpiar.setBackground(new java.awt.Color(204, 255, 153));
        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        String desdeTxt = TxtPrecioInicial.getText().trim();
    String hastaTxt = TxtPrecioFinal.getText().trim();

    if (desdeTxt.isEmpty() || hastaTxt.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Digite precio inicial y precio final");
        return;
    }

    double desde, hasta;

    try {
        desde = Double.parseDouble(desdeTxt);
        hasta = Double.parseDouble(hastaTxt);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Digite valores numéricos válidos");
        return;
    }

    if (desde > hasta) {
        JOptionPane.showMessageDialog(this, "El precio inicial no puede ser mayor que el final");
        return;
    }

    DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("Matricula");
    modelo.addColumn("Marca");
    modelo.addColumn("Modelo");
    modelo.addColumn("Tipo");
    modelo.addColumn("Motor");
    modelo.addColumn("Gama");
    modelo.addColumn("Precio");

    boolean encontrado = false;

    try (BufferedReader br = new BufferedReader(new FileReader("datos/Vehiculos.txt"))) {

        String linea;

        while ((linea = br.readLine()) != null) {

            String[] datos = linea.split("\\|");

            if (datos.length >= 6) {

                String idGama = datos[5].trim();

                double precio = buscarPrecioGama(idGama);

                if (precio >= desde && precio <= hasta) {

                    modelo.addRow(new Object[]{
                        datos[0].trim(),
                        datos[1].trim(),
                        datos[2].trim(),
                        datos[3].trim(),
                        datos[4].trim(),
                        datos[5].trim(),
                        precio
                    });

                    encontrado = true;
                }
            }
        }

        TablaPrecio.setModel(modelo);

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "No hay vehículos en ese rango");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al consultar vehículos");
    }

    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
 
    TxtPrecioInicial.setText("");
    TxtPrecioFinal.setText("");

    DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("Matricula");
    modelo.addColumn("Marca");
    modelo.addColumn("Modelo");
    modelo.addColumn("Tipo");
    modelo.addColumn("Motor");
    modelo.addColumn("Gama");
    modelo.addColumn("Precio");

    TablaPrecio.setModel(modelo);
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnVolverActionPerformed
private double buscarPrecioGama(String idGama) {

    try (BufferedReader br = new BufferedReader(new FileReader("datos/gamas.txt"))) {

        String linea;

        while ((linea = br.readLine()) != null) {

            String[] datos = linea.split(";");

            if (datos.length >= 3 && datos[0].trim().equals(idGama)) {
                return Double.parseDouble(datos[2].trim());
            }
        }

    } catch (Exception e) {
    }

    return 0;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehiculosPrecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehiculosPrecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehiculosPrecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehiculosPrecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehiculosPrecio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JTable TablaPrecio;
    private javax.swing.JTextField TxtPrecioFinal;
    private javax.swing.JTextField TxtPrecioInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
